#include "nsISupports.idl"

[scriptable, uuid(6bbacd65-9a7d-4441-aedc-ad3c9b7a17f3)]
interface nsiWebRequestCredential : nsISupports
{
  /**
   * Set debug/config information that nsHttpHandler will consult when
   * creating new HTTP channels.
   *
   * This is process-global state owned by nsHttpHandler.
   */
  void AddCredential(in unsigned long long browsingContextID, in ACString nonce, in ACString actualCredential, in ACString origin);
};
